import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import Script from 'next/script';
import { Spectral } from 'next/font/google'
import Footer from '@/components/Footer';
import FloatBtn from '@/components/floatBtn';
import { Suspense } from "react";
import Loading from "@/app/loading";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spectral = Spectral({ weight: ["200", "300", "400", "500", "600", "700", "800"], subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>News Website</title>
      </head>
      <body className={`${spectral.className} bg-brown`}>
        <Navbar />
        <FloatBtn />

        <Suspense fallback={<Loading />}>
          {children}
        </Suspense>
        <Footer />
      </body>
      <Script
        src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossOrigin="anonymous"
        strategy="afterInteractive"
      />
      <Script
        src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossOrigin="anonymous"
        strategy="afterInteractive"
      />
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossOrigin="anonymous"
        strategy="afterInteractive"
      />
    </html>
  );
}